TRAINING_ORIGINAL_DIR = "Dataset/original/training"
TESTING_ORIGINAL_DIR = "Dataset/original/testing"
TRAINING_ANNOTATION_PATH = "Dataset/original/train.csv"
TESTING_ANNOTATION_PATH = "Dataset/original/test.csv"
TRAINING_NEW_DIR = "Dataset/new/training"
TESTING_NEW_DIR = "Dataset/new/testing"
ARGUMENT_PATH = "Dataset/arguments_traning.csv"
ARGUMENT_DIR = "Dataset/arguments/"
RESIZE_SHAPE = (224, 224)